### ISSUE TITLE
It looks like `xdotool` is not installed on this computer.

### ISSUE THREAD

**Issue by kanishkaganguly** [stream-pi/server#30]
As mentioned in the title, that is the error I get when I try any of the media playback commands. I have checked, and I do have `xdotool` installed.

I am on Linux Mint 19.3 (Ubuntu 18.04)

Here is the detailed error log from the app:
```bash
java.io.IOException: Cannot run program "\xdotool": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:592)
        at java.base/java.lang.Runtime.exec(Runtime.java:416)
        at java.base/java.lang.Runtime.exec(Runtime.java:313)
        at com.stream_pi.MediaKeyAction@1.0.1/com.stream_pi.mediakeyaction.MediaKeyAction.runCommand(MediaKeyAction.java:97)
        at com.stream_pi.MediaKeyAction@1.0.1/com.stream_pi.mediakeyaction.MediaKeyAction.linuxHandler(MediaKeyAction.java:107)
        at com.stream_pi.MediaKeyAction@1.0.1/com.stream_pi.mediakeyaction.MediaKeyAction.onActionClicked(MediaKeyAction.java:76)
        at com.stream_pi.server@1.0.0-SNAPSHOT/com.stream_pi.server.controller.Controller.onNormalActionClicked(Controller.java:503)
        at com.stream_pi.server@1.0.0-SNAPSHOT/com.stream_pi.server.connection.ClientConnection$1.call(ClientConnection.java:765)
        at com.stream_pi.server@1.0.0-SNAPSHOT/com.stream_pi.server.connection.ClientConnection$1.call(ClientConnection.java:759)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 13 more
```

**Comment by rnayabed** [comment]
[Fixed](https://github.com/stream-pi/essentialactions/commit/9264f6e2aaef11dfae0d42a50ee2b86e3ec83ecc)

**Comment by rnayabed** [comment]
Redownload the server zip from releases, or download the new jar from discord

**Comment by kanishkaganguly** [comment]
Thanks, the release tag is still on 1.0.0, should I wait for an update?

**Comment by kanishkaganguly** [comment]
> Thanks, the release tag is still on 1.0.0, should I wait for an update?

Scratch that, I found the relevant post on Discord.
